### ISSUE TITLE
Search for digital content not capturing everything with a dao 

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#672]
Any component with a dao should be showing up in search results when a user selects or searches for online content. It seems like only components with digital content that is openly accessible online are displaying in the search results. For example, [World Press Freedom Committee Records](https://findingaids-beta.princeton.edu/?f%5Bcollection_sim%5D%5B%5D=World+Press+Freedom+Committee+Records%2C+1921-2009%2C+bulk+1975%2F2009&f%5Bhas_direct_online_content_ssim%5D%5B%5D=online&group=true&q=World+Press+Freedom+Committee&search_field=all_fields) has retrieved 12 folders however if you search in the current [FA site there are 81 folders available](https://findingaids.princeton.edu/?v1=World%20Press%20Freedom%20Committee&f1=kw&b1=AND&v2=&f2=kw&b2=AND&v3=&f3=kw&year=before&ed=&ld=&has-digital-content=true&start=60&rpp=10).

**Comment by faithc** [comment]
Another example: a search for editorial cartoons, limited to only online content, only yields two results, but there are many more digitized cartoons.https://findingaids-beta.princeton.edu/?f%5Bhas_direct_online_content_ssim%5D%5B%5D=online&group=true&q=editorial+cartoons&search_field=all_fields

**Comment by tpendragon** [comment]
I think both these examples are an example of search UI issues rather than indexing. For the first one, there's a keyword search for "World Press Freedom Committee" - I guess searching the collection title doesn't return the components in that collection. Should it? If I just use the collection facet, I get the proper 81: https://findingaids-beta.princeton.edu/?f%5Bcollection_sim%5D%5B%5D=World+Press+Freedom+Committee+Records%2C+1921-2009%2C+bulk+1975%2F2009&f%5Bhas_direct_online_content_ssim%5D%5B%5D=online&group=true&search_field=all_fields

The second is a similar issue (which is replicated in findingaids) - if I search "editorial cartoons" there's only 4 results. If I facet to the political cartoon collection, I get 1000. https://findingaids-beta.princeton.edu/?f%5Bcollection_sim%5D%5B%5D=Political+Cartoon+Collection%2C+1889-1944&f%5Bhas_direct_online_content_ssim%5D%5B%5D=online&group=true&q=&search_field=all_fields. Editorial cartoons is a subject heading at the collection level, so all the components aren't returning (see also https://findingaids.princeton.edu/?v1=Editorial+cartoons&f1=kw&b1=AND&v2=&f2=kw&b2=AND&v3=&f3=kw&year=before&ed=&ld=&rpp=10&start=0) 

@faithc @ccleeton What should we do here?

**Comment by faithc** [comment]
Not sure if the site is being tweaked right now, but I'm having a tough time replicating these searches, including the fact that I'm not seeing the online facet? This may warrant an in-person discussion especially to see search paths.

**Comment by tpendragon** [comment]
Marking blocked until we get a chance to poke at this together.

**Comment by tpendragon** [comment]
@faithc @ccleeton Can you look at this again? I think it's fixed with the reindex.

**Comment by faithc** [comment]
Yes, this seems better now!

**Comment by ccleeton** [comment]
@tpendragon Looks like this is still an issue.
Example a search for Woodrow Wilson
310 results in pulfa https://pulfa.princeton.edu/?v1=woodrow%20wilson&f1=kw&b1=AND&v2=&f2=kw&b2=AND&v3=&f3=kw&year=before&ed=&ld=&rpp=10&start=0&has-digital-content=true
270 results in plight https://findingaids.princeton.edu/?utf8=%E2%9C%93&group=true&search_field=all_fields&q=woodrow+wilson

**Comment by tpendragon** [comment]
Having a hard time finding one that's in PULFA but not Pulfalight so I can figure out why it's not returning.

**Comment by tpendragon** [comment]
Okay. I think the problem here is in description "Woodrow Wilson" is not matching "Woodrow Wilson's"

**Comment by ccleeton** [comment]
Here is another example that is not the 's issue
bernard baruch 
pulfalight looks like it is missing most of the results from the John Foster Dulles papers 

https://pulfa.princeton.edu/?v1=bernard%20baruch&f1=kw&b1=AND&v2=&f2=kw&b2=AND&v3=&f3=kw&year=before&ed=&ld=&rpp=10&start=0&has-digital-content=true
https://findingaids.princeton.edu/?f%5Bhas_direct_online_content_ssim%5D%5B%5D=online&group=true&q=bernard+baruch&search_field=all_fields

**Comment by tpendragon** [comment]
That one it looks like PULFA searches the full hierarchy for matches, and Pulfalight doesn't.

**Comment by faithc** [comment]
That's definitely an issue if that's the case.

**Comment by tpendragon** [comment]
@faithc @ccleeton I created https://github.com/pulibrary/pulfalight/issues/791, please prioritize it for me? I think you have one on deck slot left, after #789 is merged.

**Comment by tpendragon** [comment]
@faithc @ccleeton I think both these issues are fixed now in staging, if you want to try searching around in https://pulfalight-staging.princeton.edu and make sure it doesn't break any other relevancy.

**Comment by ccleeton** [comment]
This looks like it is working better. Seeing higher results in the online content in all searches.
